### ISSUE TITLE
SOAR Analysis

### ISSUE THREAD

**Issue by omnius45467** [omnius45467/Seasoned-Trends-Studio#8]
Comment with a link to your google doc

**Comment by Christianmorris** [comment]
https://docs.google.com/document/d/1s0tFgZsJsd2pMAmBjnIPcPO_7CqBkVnr7jLMbdKhRGo/edit

**Comment by Christianmorris** [comment]
https://docs.google.com/document/d/1cmMTZeYU4ztBSf8Pv1YfIrcsifLX5hst1MPU59BNg4o/edit
